<?php

/**
* @file
* Provides Flickity library integration for Drupal.
*/

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function flickity_theme($existing, $type, $theme, $path) {

  return array(
    'flickity' => array(
      'render element' => 'element'
    ),
    'views_view_flickity' => array(
      'variables' => array(
        'view' => NULL,
        'rows' => NULL
      )
    )
  );
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_flickity(&$variables) {

  // Flickity formatter is a clone of the default field formatter.
  template_preprocess_field($variables, NULL);
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_views_view_flickity(&$variables) {

  // Flickity views style is a clone of the default unformatted view style.
  template_preprocess_views_view_unformatted($variables);

  $config = $variables['view']->style_plugin->options['flickity_config'];

  // Attach Flickity library and set attributes.
  $variables['#attached']['library'][] = 'flickity/flickity';
  $variables['attributes'] = new Attribute(array(
    'data-flickity-options' => $config
  ));

  // Load Flickity options.
  $entity = \Drupal\flickity\Entity\Flickity::load($config);
  $variables['#attached']['drupalSettings']['flickity'][$config] = $entity->getFormattedOptions();

  // Set cache metadata.
  $variables['#cache']['tags'][] = $entity->getCacheTagsToInvalidate();
}
