flickity.flickity.*:
  type: config_entity
  label: 'Flickity configuration'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    options:
      type: mapping
      label: 'Options'
      mapping:
        cellSelector:
          type: string
          label: 'Cell selector'
        initialIndex:
          type: integer
          label: 'Initial index'
        cellAlign:
          type: string
          label: 'Cell align'
        setGallerySize:
          type: boolean
          label: 'Set gallery size'
        resize:
          type: boolean
          label: 'Resize'
        contain:
          type: boolean
          label: 'Contain'
        draggable:
          type: boolean
          label: 'Draggable'
        freeScroll:
          type: boolean
          label: 'Free scroll'
        wrapAround:
          type: boolean
          label: 'Wrap around'
        autoPlay:
          type: integer
          label: 'Auto play'
        adaptiveHeight:
          type: boolean
          label: 'Adaptive height'
        prevNextButtons:
          type: boolean
          label: 'Prev/Next buttons'
        pageDots:
          type: boolean
          label: 'Page dots'
        advanced:
          type: text
          label: 'Advanced options'
