flickity.flickity.*:
  type: config_entity
  label: 'Flickity'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    options:
      type: text
      label: 'Options'
